Fix build error on GCC 15
`-Wincompatible-pointer-types` leads to an error on GCC 15 probably due to the default C23 standard.

This small change fixes the following build error:

```
[2/5] Building C object CMakeFiles/catimg.dir/src/catimg.c.o
FAILED: [code=1] CMakeFiles/catimg.dir/src/catimg.c.o
/usr/bin/cc  -I/build/catimg/src/catimg/src -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/catimg/src=/usr/src/debug/catimg -flto=auto -fcommon -MD -MT CMakeFiles/catimg.dir/src/catimg.c.o -MF CMakeFiles/catimg.dir/src/catimg.c.o.d -o CMakeFiles/catimg.dir/src/catimg.c.o -c /build/catimg/src/catimg/src/catimg.c
/build/catimg/src/catimg/src/catimg.c: In function ‘main’:
/build/catimg/src/catimg/src/catimg.c:170:24: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  170 |         signal(SIGINT, intHandler);
      |                        ^~~~~~~~~~
      |                        |
      |                        void (*)(void)
In file included from /build/catimg/src/catimg/src/catimg.c:7:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
/build/catimg/src/catimg/src/catimg.c:37:6: note: ‘intHandler’ declared here
   37 | void intHandler() {
      |      ^~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
```